# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Education"
  url = "/education"
  weight = 2


[[main]]
  name = "Research"  # Title of the link.
  url = "#publications"  # Widget Page folder name.
  weight = 3  # Position of the link in the navigation bar.

[[main]]
name = "Projects"
url = "#projects"
weight = 4

[[main]]
name = "Notes"
url = "/notes"
weight = 5

[[main]]
name = "Posts"
url = "#posts"
weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7





# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70

