baseURL : "https://jhossain.me/"
languageCode: en-us
title: "Jubayer Hossain"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable Disqus forum
disqusShortname: https-jhossain-me

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Copyright Notice
  copyright: © 2020 Jubayer Hossain.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Hey there! This is Jubayer Hossain. Welcome to my personal website.

  # Background image of the landing page
  background: "images/bg.gif"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  # logo:
  #   main: /assets/images/main_logo.png
  #   inverted: /assets/images/inverted_logo.png

  # GitHub repo URL of your site
  # gitRepo: https://github.com/hossainlab/jhossain.me

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: Blog
    url: https://hossainlab.github.io/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # some information about you
  author:
    #name: "Jubayer Hossain"
    #nickname: "Jubayer"
    image: "/images/focus.jpg"
    # give your contact information. they will be used in the footer
    contactInfo:
      email: "jubayer@hdrobd.org"
      #phone: "+8801771083855"
    # a summary of what you do
    # summary:
    # - Welcome to my personal website!
    # - Mostly, I work with Python.
    # - I love to work with team.
    # - Currently, I am working at HDRO
