---
title: Introduction to R 
author: Jubayer Hossain
date: '2021-04-22'
slug: introduction-to-r
categories: [R Programming]
tags:
  - R 
  - Basics
description: R is a programming language and environment commonly used in statistical computing, data analytics and scientific research.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
# draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  comment = NA,
  fig.align = "center",
  out.width='100%'
)
options(scipen = 999)
```

## What is R{.t}
- R is a dialect of S(R is an implementation of the S programming language).  
- R was created by Ross Ihaka and Robert Gentleman at the University of Auckland, New
Zealand, and is developed by the R Development Core Team. 
- R is a programming language and environment commonly used in statistical computing, data analytics and scientific research. 
- R is a programming language and free software environment for statistical computing and graphics supported by the R Foundation for Statistical Computing. 
- The R language is widely used among statisticians and data miners for developing statistical software and data analysis.

## Why R?{.t}
- R is open source and free! 
  - R is free to download as it is licensed under the terms of the GNU General Public License.
  - You can look at the source to see what’s happening under the hood.
  - There’s more, most R packages are available under the same license so you can use them, even in     commercial applications without having to call your lawyer. 

- R is popular – and increasing in popularity. 
- R runs on all platforms.(Windows, Linux and Mac) 
- R is being used by the biggest tech giants(google, facebook, microsoft, twitter)

## Applications of R{.t}
- Data Science
- Data Analysis
- Genomic Data Science
- Biological Data Analysis
- Mutational Signature Analysis
- Genomic Analysis
- Statistical Computing
- Machine Learning


## R Packages for Data Analysis/Data Science{.t}
- `dplyr`
  - dplyr is a grammar of data manipulation, providing a consistent set of verbs that help you solve  the most common data manipulation challenges
  - Documentation- https://dplyr.tidyverse.org/
- `ggplot2`
  - ggplot2 is a data visualization package for the statistical programming language R.
  - Created by Hadley Wickham in 2005, ggplot2 is an implementation of Leland Wilkinson's Grammar of Graphics—a general scheme for data visualization which breaks up graphs into semantic components such as scales and layers.
  - https://ggplot2.tidyverse.org/

- Plotly 
  - Plotly's R graphing library makes interactive, publication-quality graphs. 
  - https://plotly.com/r/
- Leaflet 
  - Leaflet is one of the most popular open-source JavaScript libraries for interactive maps.
  - It’s used by websites ranging from The New York Times and The Washington Post to GitHub and Flickr, as well as GIS specialists like OpenStreetMap, Mapbox, and CartoDB.
  - https://rstudio.github.io/leaflet/

- tidyverse
  - The tidyverse is an opinionated collection of R packages designed for data science.
  - All packages share an underlying design philosophy, grammar, and data structures.
  - https://www.tidyverse.org/ 
  

## R Packages for Bioinformatics/Genomic Data Science{.t}
- Bioconductor
  - Bioconductor is a free, open source and open development software project for the analysis and comprehension of genomic data generated by wet lab experiments in molecular biology.
  - Bioconductor is based primarily on the statistical R programming language, but does contain contributions in other programming languages.
  - https://www.bioconductor.org/
- seqinr
  - Exploratory data analysis and data visualization for biological sequence (DNA and protein) data.
  - https://cran.r-project.org/web/packages/seqinr/index.html 
- MutatioanlPattern
  - Mutational processes leave characteristic footprints in genomic DNA.
  - https://bioconductor.org/packages/release/bioc/html/MutationalPatterns.html 
  
  
## Resources: Books {.t}
* [R for Data Science by Roger D.Peng ](https://bookdown.org/rdpeng/rprogdatascience/)
* [Introduction to Data Science by Rafael Irizarry](https://rafalab.github.io/dsbook/)
* [Data Analysis for the Life Sciences by Rafael Irizarry](https://rafalab.github.io/pagesharvardx.html)
* [Exploratory Data Analysis with R by Roger D.Peng ](https://bookdown.org/rdpeng/rprogdatascience/)

## Resources: Blogs{.t}
- https://www.datamentor.io/r-programming/
- https://online.stat.psu.edu/stat484/
- https://online.stat.psu.edu/stat485/
- https://www.statmethods.net/index.html
- https://simplystatistics.org/
- https://www.tutorialspoint.com/r/index.htm
- https://www.rforbiologists.org/
- https://compgenomr.github.io/book/
- https://statsandr.com/
- https://rafalab.github.io/pages/harvardx.html
- https://bolt.mph.ufl.edu/software/r-phc-6055/


## Alternatives to R Programming{.t}
- Python 
  - Python is a very powerful high-level, object-oriented programming language with an easy-to-use and simple syntax.
  - Python is extremely popular among data scientists and researchers. Most of the packages in R have equivalent libraries in Python as well.
  
- SAS (Statistical Analysis System)
  - SAS is a powerful software that has been the first choice of private enterprise for their analytics needs for a long time.

- SPSS – Software Package for Statistical Analysis
  - SPSS is another popular statistical tool. It is used most commonly in the social sciences and is considered the easiest to learn among enterprise statistical tools.


## Installing R {.t}
- Installing R on Windows -
https://cran.r-project.org/bin/windows/base/
- Installing R on Linux -
https://cran.r-project.org/bin/linux/ubuntu/README.html
- Installing R on Mac - 
https://cran.r-project.org/bin/macosx/

## Installing RStudio{.t}
- RStudio is an Integrated Development Environment(IDE) available for R that is built by RStudio. 
- Download and Install
https://rstudio.com/products/rstudio/download/#download
